# Generated by Django 4.1.3 on 2022-11-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('year_of_manufacture', models.IntegerField()),
                ('weight', models.FloatField()),
                ('condition', models.CharField(max_length=200)),
                ('notes', models.TextField()),
            ],
        ),
    ]
